[
  { id: 1, content: "本屋", english_content: 'Book Store'},
  { id: 2, content: "東京", english_content: 'Tokyo'},
  { id: 3, content: "貧乏人", english_content: 'Poor'},
  { id: 4, content: "金持ち", english_content: 'Rich'},
  { id: 5, content: "社会人", english_content: 'Shakaizin'},
  { id: 6, content: "老人ホーム", english_content: 'Old Home'},
  { id: 7, content: "宇宙", english_content: 'Space'},
  { id: 8, content: "酒", english_content: 'Alcohol'},
  { id: 9, content: "鈴木の家", english_content: "Suzuki's House"},
  { id: 10, content: "美女", english_content: 'Beauth'},
  { id: 11, content: "イケメン", english_content: 'Handsome'},
  { id: 12, content: "赤ちゃん", english_content: 'Baby'},
  { id: 13, content: "大人", english_content: 'Adult'},
  { id: 14, content: "破局", english_content: 'Goodbye'},
  { id: 15, content: "卒業", english_content: 'Graduation'},
  { id: 16, content: "幼稚園", english_content: 'Kindergarten'},
  { id: 17, content: "結婚", english_content: 'Marriage'},
  { id: 18, content: "どこか", english_content: 'Somewhere'},
  { id: 19, content: "老い", english_content: 'Old'},
  { id: 20, content: "月", english_content: 'Moon'},
  { id: 21, content: "南極", english_content: 'Antarctic'},
  { id: 22, content: "魔界", english_content: 'Makai'},
  { id: 23, content: "二次元", english_content: 'Nizigen'},
  { id: 24, content: "社会", english_content: 'Society'},
  { id: 25, content: "トイレ", english_content: 'Toilet'},
  { id: 26, content: "職場", english_content: 'Office' },
  { id: 27, content: "死", english_content: 'Death' },
  { id: 28, content: "自宅", english_content: 'Home' },
  { id: 29, content: "天国", english_content: 'Heaven' },
  { id: 30, content: "地獄", english_content: 'Hell' },
].each do |item|
  document = Document.new(item)
  document.save!
end